FROM wyveo/nginx-php-fpm:php81
EXPOSE 81
RUN mkdir -p /var/log/nginx/
RUN mkdir -p /var/www/
RUN mkdir -p /var/www/todo_api
RUN chmod -R 777 /var/www/
RUN chmod -R 777 /var/www/todo_api
RUN chmod -R 777 /var/log/nginx/
RUN apt -y update
RUN apt -y upgrade
RUN apt install -y php-sqlite3 sqlite3 libsqlite3-dev

COPY ./Docker/nginx/default.conf /etc/nginx/conf.d/