version: "3.9"

services:
  dev:
    build:
        context: .
        dockerfile: DockerFile
    container_name: todo_api
    image: todo_api:1.0.0
    ports:
        - 81:80
    volumes:
        - .:/var/www/todo_api/
    networks:
        - laravel
    environment:
        - DB_PORT=3306
        - DB_HOST=mysql
    depends_on:
        - mysql
      
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
        - 3308:3306
    volumes: 
        - dbdata:/var/lib/mysql
        - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
        MYSQL_DATABASE: todoApi
        MYSQL_USER: todolist
        MYSQL_PASSWORD: laravelApplication
        MYSQL_ROOT_PASSWORD: laravelApplication
        MYSQL_ALLOW_EMPTY_PASSWORD: "YES"
    networks:
        - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local