name: Laravel Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect with to deploy application 
        uses: appleboy/ssh-action@v1.0.0
        with: 
          username: root
          host: '137.184.15.127'
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: 'cd /var/www/todo_api && /bin/sh ./deploy.sh'